import {rotateSelection} from './selection-rotation.js';
import {rotationPlaneAt} from './rotation-hover.js';
import {bindRepeatButton} from './repeat-button.js';
import * as THREE from 'three';
import {moveAlongAxis,movementDirection,axisDragDistance,parseDisplacement} from './axis-move.js';
export function setupAxisGizmo({read,camera,controls,change,refresh,readPivot=()=>null,showError}){const $=id=>document.getElementById(id),box=$('axis-gizmo'),svg=$('axis-gizmo-svg'),input=$('axis-distance'),NS='http://www.w3.org/2000/svg',colors={x:'#f39187',y:'#85dcc0',z:'#90baff',direction:'#ffdc72'};let ids=[],operation=null,drag=null,directions={},key='',tilt=0,rotationMode=false,rotationPlane='xy',baseAxis='x',rotations={xz:0,yz:0};let cursor=null,objectMode='move',rotationState=null,objectAngles={xy:0,xz:0,yz:0};const modeInput=$('axis-transform-mode');const rotationInput=$('axis-rotation');
const directionAngles=()=>({baseAxis,xy:tilt,...rotations}),rotationValue=()=>objectMode==='rotate'?objectAngles[rotationPlane]:rotationPlane==='xy'?tilt:rotations[rotationPlane],rotationLabel=()=>{$('axis-rotation-row').querySelector('label').textContent='Obrót '+rotationPlane.toUpperCase();};
const node=(tag,attrs)=>{const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;};
function sizeRotationValue(){rotationInput.style.width=Math.max(1,Math.min(12,rotationInput.value.length))+'ch';}
rotationInput.addEventListener('input',sizeRotationValue);
function render(){$('axis-rotation-row').hidden=!ids.length||objectMode!=='rotate';for(const mode of ['move','rotate']){const button=$('axis-mode-'+mode);button.classList.toggle('active',objectMode===mode);button.setAttribute('aria-pressed',String(objectMode===mode));}sizeRotationValue();if(!ids.length)return;const q=camera().quaternion.clone().invert(),next={};for(const axis of ['x','y','z','direction']){const v=movementDirection(axis,directionAngles()).applyQuaternion(q);next[axis]={x:v.x,y:-v.y,z:v.z};}const hovered=drag?.rotation?rotationPlane:rotationPlaneAt(cursor,next);const signature=JSON.stringify([next,operation?.axis,rotationMode,rotationPlane,hovered]);if(signature===key)return;key=signature;directions=next;svg.replaceChildren();node('circle',{cx:100,cy:100,r:5,fill:'#c2d4de'});for(const axis of ['x','y','z','direction']){const d=next[axis],length=Math.hypot(d.x,d.y),arrowLength=axis==='direction'?38:76,end=length>.12?{x:100+d.x*arrowLength,y:100+d.y*arrowLength}:{x:100,y:100-arrowLength},active=operation?.axis===axis;node('line',{x1:100,y1:100,x2:end.x,y2:end.y,stroke:colors[axis],'stroke-width':active?4:2.5,'pointer-events':'none'});const angle=Math.atan2(end.y-100,end.x-100),a=angle+2.6,b=angle-2.6;node('path',{d:`M${end.x+9*Math.cos(a)} ${end.y+9*Math.sin(a)} L${end.x} ${end.y} L${end.x+9*Math.cos(b)} ${end.y+9*Math.sin(b)}`,fill:'none',stroke:colors[axis],'stroke-width':2.5,'pointer-events':'none'});node('line',{x1:100,y1:100,x2:end.x,y2:end.y,stroke:'transparent','stroke-width':18,'data-axis':axis,'pointer-events':'stroke',role:'button','aria-label':axis==='direction'?'Przesuń w ustawionym kierunku':'Przesuń w osi '+axis.toUpperCase(),tabindex:0});if(axis==='direction')continue;const label=node('text',{x:end.x+8,y:end.y-7,fill:colors[axis],'font-size':14,'pointer-events':'none'});label.textContent=axis.toUpperCase()+(length<=.12?' ⊙':'');}for(const plane of ['xy','xz','yz']){const [first,second]=plane;const arc=Array.from({length:33},(_,i)=>{const angle=i/32*Math.PI/2;return `${i?'L':'M'}${100+66*(next[first].x*Math.cos(angle)+next[second].x*Math.sin(angle))} ${100+66*(next[first].y*Math.cos(angle)+next[second].y*Math.sin(angle))}`;}).join(' ');node('path',{d:arc,fill:'none',stroke:'#80b6d5',visibility:hovered===plane?'visible':'hidden','stroke-width':rotationMode&&rotationPlane===plane?2.5:1.5,'pointer-events':'none'});node('path',{d:arc,fill:'none',stroke:'transparent','stroke-width':14,'pointer-events':hovered===plane?'stroke':'none','data-rotation':plane,role:'button',tabindex:0,'aria-label':'Obrót kierunku '+plane.toUpperCase()});}}
function apply(amount,commit=false){if(!operation)return;try{change(moveAlongAxis(operation.base,operation.ids,operation.axis,amount,operation.tilt??0),commit);operation.amount=amount;if(commit)operation.committed=structuredClone(read());refresh();}catch(e){showError(e);}}
function rebaseMovement(){if(operation){operation.base=structuredClone(read());operation.committed=structuredClone(read());operation.amount=0;operation.tilt=directionAngles();input.value='0';}}
function beginRotation(){rotationState={base:structuredClone(read()),ids:[...ids],plane:rotationPlane,pivot:structuredClone(readPivot()),startAngle:rotationValue(),committed:structuredClone(read())};}
function choose(axis){rotationState=null;if(axis!=='direction'){baseAxis=axis;tilt=0;rotations={xz:0,yz:0};}rotationMode=false;$('axis-rotation-row').hidden=objectMode!=='rotate';rotationInput.value=String(rotationValue());rotationLabel();operation={axis,tilt:directionAngles(),ids:[...ids],base:structuredClone(read()),committed:structuredClone(read()),amount:0};$('axis-distance-label').textContent=axis==='direction'?'Przesunięcie':'Przesunięcie '+axis.toUpperCase();$('axis-value-row').hidden=false;input.value='0';key='';render();}
function chooseRotation(plane='xy'){rotationPlane=plane;rotationLabel();rotationMode=true;if(objectMode==='rotate')beginRotation();$('axis-value-row').hidden=false;$('axis-rotation-row').hidden=objectMode!=='rotate';rotationInput.value=String(rotationValue());key='';render();}
function rotate(value,commit=false){
 try{
  if(objectMode==='rotate'){
   if(!rotationState||rotationState.plane!==rotationPlane)beginRotation();
   change(rotateSelection(rotationState.base,rotationState.ids,rotationPlane,value-rotationState.startAngle,rotationState.pivot),commit);
   objectAngles[rotationPlane]=value;if(commit)rotationState.committed=structuredClone(read());refresh();rebaseMovement();
  }else{if(rotationPlane==='xy')tilt=value;else rotations[rotationPlane]=value;if(operation)operation.axis='direction';$('axis-distance-label').textContent='Przesunięcie';rebaseMovement();}
  rotationInput.value=String(Math.round(value*10)/10);key='';render();
 }catch(error){showError(error);}
}
for(const mode of ['move','rotate'])$('axis-mode-'+mode).addEventListener('click',()=>{if(mode===objectMode)return;modeInput.value=mode;modeInput.dispatchEvent(new Event('input',{bubbles:true}));modeInput.dispatchEvent(new Event('change',{bubbles:true}));});
modeInput.addEventListener('change',()=>{cancelDrag();objectMode=modeInput.value;rotationState=null;objectAngles={xy:0,xz:0,yz:0};rotationInput.value=String(rotationValue());rebaseMovement();key='';render();});
rotationInput.addEventListener('change',()=>{const value=parseDisplacement(rotationInput.value);if(value!==null&&objectMode==='rotate')rotate(value,true);});
rotationInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const value=parseDisplacement(rotationInput.value);if(value!==null){rotate(value,objectMode==='rotate');recordRotation();rotationInput.select();}}});

function recordRotation(){rotationInput.dispatchEvent(new Event('change',{bubbles:true}));}
rotationInput.addEventListener('input',()=>{const value=parseDisplacement(rotationInput.value);if(value!==null)rotate(value);});
for(const [id,step] of [['axis-rotation-minus',-1],['axis-rotation-plus',1]])bindRepeatButton($(id),()=>{rotate(rotationValue()+step);recordRotation();});
svg.addEventListener('pointerdown',e=>{if(e.button===0&&e.target.getAttribute('data-rotation')){e.preventDefault();e.stopPropagation();chooseRotation(e.target.getAttribute('data-rotation'));drag={id:e.pointerId,start:{x:e.clientX,y:e.clientY},rotation:true,tilt:rotationValue()};controls().enabled=false;if(e.isTrusted)svg.setPointerCapture(e.pointerId);return;}const axis=e.target.getAttribute('data-axis');if(e.button!==0||!axis)return;e.preventDefault();e.stopPropagation();choose(axis);drag={id:e.pointerId,start:{x:e.clientX,y:e.clientY},direction:{...directions[axis]}};controls().enabled=false;if(e.isTrusted)svg.setPointerCapture(e.pointerId);});
svg.addEventListener('pointermove',e=>{if(!drag){const point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const local=point.matrixTransform(svg.getScreenCTM().inverse());cursor={x:local.x-100,y:local.y-100};render();return;}if(drag?.id!==e.pointerId)return;if(drag.rotation){rotate(drag.tilt+(drag.start.y-e.clientY)*.5);return;}const amount=axisDragDistance(drag.start,{x:e.clientX,y:e.clientY},drag.direction);apply(Math.round(amount*10)/10);input.value=operation.amount.toFixed(1);});
svg.addEventListener('pointerup',e=>{if(drag?.id!==e.pointerId)return;const wasRotation=drag.rotation;drag=null;controls().enabled=true;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);if(wasRotation){recordRotation();if(objectMode==='rotate'){rotationInput.focus();rotationInput.select();}else{input.focus();input.select();}}else{apply(operation.amount,true);input.focus();input.select();}});
function cancelDrag(){if(!drag)return;const previous=drag;drag=null;if(previous.rotation){rotate(previous.tilt);controls().enabled=true;return;}if(operation)change(operation.base,false);controls().enabled=true;refresh();}
svg.addEventListener('pointerleave',()=>{cursor=null;key='';render();});
svg.addEventListener('pointercancel',cancelDrag);svg.addEventListener('lostpointercapture',cancelDrag);window.addEventListener('blur',cancelDrag);
svg.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.getAttribute('data-rotation')){e.preventDefault();chooseRotation(e.target.getAttribute('data-rotation'));if(objectMode==='rotate'){rotationInput.focus();rotationInput.select();}else{input.focus();input.select();}return;}if((e.key==='Enter'||e.key===' ')&&e.target.getAttribute('data-axis')){e.preventDefault();choose(e.target.getAttribute('data-axis'));input.focus();input.select();}});
input.addEventListener('input',()=>{const value=parseDisplacement(input.value);input.setCustomValidity(value===null?'Wpisz przesunięcie w centymetrach.':'');if(value!==null)apply(value);});
input.addEventListener('change',()=>{const value=parseDisplacement(input.value);if(value!==null)apply(value,true);});
input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const value=parseDisplacement(input.value);if(value!==null){apply(value,true);input.select();}}});
return {pivotChanged(){cancelDrag();rotationState=null;objectAngles={xy:0,xz:0,yz:0};rotationInput.value=String(rotationValue());key='';render();},capture(){return {ids:[...ids],operation:structuredClone(operation),value:input.value,tilt,rotationMode,rotationPlane,baseAxis,objectMode,objectAngles:{...objectAngles},rotationState:structuredClone(rotationState),rotations:{...rotations}};},restore(state){cancelDrag();objectMode=state.objectMode??'move';modeInput.value=objectMode;objectAngles={xy:0,xz:0,yz:0,...state.objectAngles};rotationState=structuredClone(state.rotationState??null);tilt=state.tilt??0;baseAxis=state.baseAxis??'x';rotations={xz:0,yz:0,...state.rotations};rotationPlane=state.rotationPlane??'xy';rotationLabel();rotationMode=state.rotationMode??false;rotationInput.value=String(rotationValue());$('axis-rotation-row').hidden=!ids.length||objectMode!=='rotate';ids=[...state.ids];operation=structuredClone(state.operation);box.hidden=!ids.length;if(ids.length&&!operation)choose('x');$('axis-value-row').hidden=!operation;input.value=state.value;if(operation){$('axis-distance-label').textContent=operation.axis==='direction'?'Przesunięcie':'Przesunięcie '+operation.axis.toUpperCase();operation.committed=structuredClone(read());}key='';render();},sync(next){cancelDrag();if(operation&&JSON.stringify(ids)===JSON.stringify(next)){const axis=operation.axis,direction=movementDirection(axis,operation.tilt??0),delta=operation.ids.reduce((sum,i)=>{const current=read().vertices[i],initial=operation.base.vertices[i];return sum+(current?new THREE.Vector3(current.x-initial.x,current.y-initial.y,current.z-initial.z).dot(direction):0);},0)/operation.ids.length*100;operation.amount=delta;operation.committed=structuredClone(read());input.value=Number(delta.toFixed(6)).toString();box.hidden=!next.length;key='';render();}else this.reset(next);},render,reset(next){cancelDrag();rotationState=null;objectAngles={xy:0,xz:0,yz:0};ids=[...next];operation=null;box.hidden=!ids.length;if(ids.length)choose('x');else $('axis-value-row').hidden=true;key='';render();},clear(){cancelDrag();if(operation&&document.activeElement===input)change(operation.committed,false);operation=null;ids=[];box.hidden=true;controls().enabled=true;},get active(){return !!drag||document.activeElement===input||document.activeElement===rotationInput||document.activeElement===modeInput;}};
}
