import * as THREE from 'three';
import {moveAlongAxis,axisDragDistance,parseDisplacement} from './axis-move.js';
export function setupAxisGizmo({read,camera,controls,change,refresh,showError}){const $=id=>document.getElementById(id),box=$('axis-gizmo'),svg=$('axis-gizmo-svg'),input=$('axis-distance'),NS='http://www.w3.org/2000/svg',colors={x:'#f39187',y:'#85dcc0',z:'#90baff'};let ids=[],operation=null,drag=null,directions={},key='';
const node=(tag,attrs)=>{const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;};
function render(){if(!ids.length)return;const q=camera().quaternion.clone().invert(),next={};for(const axis of ['x','y','z']){const v=new THREE.Vector3(axis==='x'?1:0,axis==='y'?1:0,axis==='z'?1:0).applyQuaternion(q);next[axis]={x:v.x,y:-v.y,z:v.z};}const signature=JSON.stringify([next,operation?.axis]);if(signature===key)return;key=signature;directions=next;svg.replaceChildren();node('circle',{cx:100,cy:100,r:5,fill:'#c2d4de'});for(const axis of ['x','y','z']){const d=next[axis],length=Math.hypot(d.x,d.y),end=length>.12?{x:100+d.x*76,y:100+d.y*76}:{x:100,y:100-76},active=operation?.axis===axis;node('line',{x1:100,y1:100,x2:end.x,y2:end.y,stroke:colors[axis],'stroke-width':active?4:2.5,'pointer-events':'none'});const angle=Math.atan2(end.y-100,end.x-100),a=angle+2.6,b=angle-2.6;node('path',{d:`M${end.x+9*Math.cos(a)} ${end.y+9*Math.sin(a)} L${end.x} ${end.y} L${end.x+9*Math.cos(b)} ${end.y+9*Math.sin(b)}`,fill:'none',stroke:colors[axis],'stroke-width':2.5,'pointer-events':'none'});node('line',{x1:100,y1:100,x2:end.x,y2:end.y,stroke:'transparent','stroke-width':18,'data-axis':axis,'pointer-events':'stroke',role:'button','aria-label':'Przesuń w osi '+axis.toUpperCase(),tabindex:0});const label=node('text',{x:end.x+8,y:end.y-7,fill:colors[axis],'font-size':14,'pointer-events':'none'});label.textContent=axis.toUpperCase()+(length<=.12?' ⊙':'');}}
function apply(amount,commit=false){if(!operation)return;try{change(moveAlongAxis(operation.base,operation.ids,operation.axis,amount),commit);operation.amount=amount;if(commit)operation.committed=structuredClone(read());refresh();}catch(e){showError(e);}}
function choose(axis){operation={axis,ids:[...ids],base:structuredClone(read()),committed:structuredClone(read()),amount:0};$('axis-distance-label').textContent='Przesunięcie '+axis.toUpperCase();$('axis-value-row').hidden=false;input.value='0';key='';render();}
svg.addEventListener('pointerdown',e=>{const axis=e.target.getAttribute('data-axis');if(e.button!==0||!axis)return;e.preventDefault();e.stopPropagation();choose(axis);drag={id:e.pointerId,start:{x:e.clientX,y:e.clientY},direction:{...directions[axis]}};controls().enabled=false;if(e.isTrusted)svg.setPointerCapture(e.pointerId);});
svg.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;const amount=axisDragDistance(drag.start,{x:e.clientX,y:e.clientY},drag.direction);apply(Math.round(amount*10)/10);input.value=operation.amount.toFixed(1);});
svg.addEventListener('pointerup',e=>{if(drag?.id!==e.pointerId)return;drag=null;controls().enabled=true;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);apply(operation.amount,true);input.focus();input.select();});
function cancelDrag(){if(!drag)return;drag=null;if(operation)change(operation.base,false);controls().enabled=true;refresh();}
svg.addEventListener('pointercancel',cancelDrag);svg.addEventListener('lostpointercapture',cancelDrag);window.addEventListener('blur',cancelDrag);
svg.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.getAttribute('data-axis')){e.preventDefault();choose(e.target.getAttribute('data-axis'));input.focus();input.select();}});
input.addEventListener('input',()=>{const value=parseDisplacement(input.value);input.setCustomValidity(value===null?'Wpisz przesunięcie w centymetrach.':'');if(value!==null)apply(value);});
input.addEventListener('change',()=>{const value=parseDisplacement(input.value);if(value!==null)apply(value,true);});
input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const value=parseDisplacement(input.value);if(value!==null){apply(value,true);input.select();}}});
return {capture(){return {ids:[...ids],operation:structuredClone(operation),value:input.value};},restore(state){cancelDrag();ids=[...state.ids];operation=structuredClone(state.operation);box.hidden=!ids.length;if(ids.length&&!operation)choose('x');$('axis-value-row').hidden=!operation;input.value=state.value;if(operation){$('axis-distance-label').textContent='Przesunięcie '+operation.axis.toUpperCase();operation.committed=structuredClone(read());}key='';render();},sync(next){cancelDrag();if(operation&&JSON.stringify(ids)===JSON.stringify(next)){const axis=operation.axis,delta=operation.ids.reduce((sum,i)=>sum+(read().vertices[i]?.[axis]??0)-operation.base.vertices[i][axis],0)/operation.ids.length*100;operation.amount=delta;operation.committed=structuredClone(read());input.value=Number(delta.toFixed(6)).toString();box.hidden=!next.length;key='';render();}else this.reset(next);},render,reset(next){cancelDrag();ids=[...next];operation=null;box.hidden=!ids.length;if(ids.length)choose('x');else $('axis-value-row').hidden=true;key='';render();},clear(){cancelDrag();if(operation&&document.activeElement===input)change(operation.committed,false);operation=null;ids=[];box.hidden=true;controls().enabled=true;},get active(){return !!drag||document.activeElement===input;}};
}
