import * as THREE from 'three';
import {initialFootprint,normalizeFootprint,recessEdge,bevelVertex} from './surface-model.js';
function partialNicheMesh(p,height,nicheTop,leftFront,rightFront){
 const n=p.length,outer=[...Array(leftFront+1).keys(),...Array.from({length:n-rightFront},(_,i)=>rightFront+i)];
 const vertices=[...p.map(v=>({x:v.x,y:0,z:v.z})),...p.map(v=>({x:v.x,y:nicheTop,z:v.z})),...outer.map(i=>({x:p[i].x,y:height,z:p[i].z}))];
 const mid=i=>i+n,top=new Map(outer.map((i,j)=>[i,2*n+j]));
 const faces=[{id:'floor',indices:p.map((_,i)=>i)},{id:'ceiling',indices:outer.map(i=>top.get(i)).reverse()}];
 for(let i=0;i<n;i++)faces.push({id:'wall-edge-'+i,indices:[i,mid(i),mid((i+1)%n),(i+1)%n]});
 for(let i=0;i<n;i++)if(i<leftFront||i>=rightFront){const j=(i+1)%n;faces.push({id:'wall-upper-'+i,indices:[mid(i),top.get(i),top.get(j),mid(j)]});}
 faces.push({id:'wall-front-upper',indices:[mid(leftFront),top.get(leftFront),top.get(rightFront),mid(rightFront)]});
 faces.push({id:'niche-roof',indices:Array.from({length:rightFront-leftFront+1},(_,i)=>mid(rightFront-i))});
 return {vertices,faces};
}
export function initialRoomMesh(doc){
 const p=normalizeFootprint(doc.roomShape??initialFootprint(doc)),n=p.length,h=doc.room.height;
 const niche=doc.roomFeatures?.window,shift=doc.transforms?.window??{};
 if(!doc.roomShape&&n===8&&niche&&niche.bottom+(shift.y??0)<=.001&&niche.height<h-.002)return partialNicheMesh(p,h,niche.bottom+niche.height+(shift.y??0),1,4);
 return {vertices:[...p.map(v=>({x:v.x,y:0,z:v.z})),...p.map(v=>({x:v.x,y:h,z:v.z}))],faces:[{id:'floor',indices:p.map((_,i)=>i)},{id:'ceiling',indices:p.map((_,i)=>2*n-1-i)},...p.map((_,i)=>({id:'wall-edge-'+i,indices:[i,i+n,(i+1)%n+n,(i+1)%n]}))]};
}
export function normalizeRoomMesh(input){if(input==null)return null;if(!Array.isArray(input.vertices)||input.vertices.length<4||input.vertices.length>512||!Array.isArray(input.faces)||input.faces.length<4||input.faces.length>512)throw new Error('Nieprawidłowa siatka pokoju.');const mesh=structuredClone(input);for(const p of mesh.vertices)if(!p||![p.x,p.y,p.z].every(Number.isFinite)||Math.max(Math.abs(p.x),Math.abs(p.y),Math.abs(p.z))>100)throw new Error('Nieprawidłowy punkt pokoju.');const ids=new Set(),edges=new Map();for(const f of mesh.faces){if(typeof f.id!=='string'||ids.has(f.id)||!Array.isArray(f.indices)||f.indices.length<3||new Set(f.indices).size!==f.indices.length||f.indices.some(i=>!Number.isInteger(i)||!mesh.vertices[i]))throw new Error('Nieprawidłowa powierzchnia.');ids.add(f.id);let area=new THREE.Vector3();for(let j=0;j<f.indices.length;j++){const a=mesh.vertices[f.indices[j]],b=mesh.vertices[f.indices[(j+1)%f.indices.length]];if(new THREE.Vector3(a.x,a.y,a.z).distanceTo(new THREE.Vector3(b.x,b.y,b.z))<.002)throw new Error('Krawędź jest zbyt krótka.');area.add(new THREE.Vector3(a.x,a.y,a.z).cross(new THREE.Vector3(b.x,b.y,b.z)));const key=[f.indices[j],f.indices[(j+1)%f.indices.length]].sort((a,b)=>a-b).join(':');edges.set(key,(edges.get(key)??0)+1);}if(area.length()<.00002)throw new Error('Powierzchnia jest zdegenerowana.');}if([...edges.values()].some(n=>n!==2))throw new Error('Ściany muszą tworzyć zamknięty pokój.');return mesh;}
export function meshEdges(mesh){const edges=new Map();for(const f of mesh.faces)for(let i=0;i<f.indices.length;i++){const pair=[f.indices[i],f.indices[(i+1)%f.indices.length]].sort((a,b)=>a-b);edges.set(pair.join(':'),pair);}return [...edges.values()];}
export function transformMesh(mesh,indices,position,rotation){const next=structuredClone(mesh),points=indices.map(i=>new THREE.Vector3(mesh.vertices[i].x,mesh.vertices[i].y,mesh.vertices[i].z)),center=points.reduce((s,p)=>s.add(p),new THREE.Vector3()).multiplyScalar(1/points.length),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...['x','y','z'].map(k=>THREE.MathUtils.degToRad(rotation[k])),'XYZ')),target=new THREE.Vector3(position.x,position.y,position.z);for(const i of indices){const p=new THREE.Vector3(mesh.vertices[i].x,mesh.vertices[i].y,mesh.vertices[i].z).sub(center).applyQuaternion(q).add(target);next.vertices[i]={x:p.x,y:p.y,z:p.z};}return normalizeRoomMesh(next);}
export function dissolveMesh(mesh,indices){const remove=new Set(indices),next=structuredClone(mesh);next.faces=next.faces.map(f=>({...f,indices:f.indices.filter(i=>!remove.has(i))}));const used=[...new Set(next.faces.flatMap(f=>f.indices))].sort((a,b)=>a-b),map=new Map(used.map((id,i)=>[id,i]));next.vertices=used.map(i=>next.vertices[i]);next.faces.forEach(f=>f.indices=f.indices.map(i=>map.get(i)));return normalizeRoomMesh(next);}
export function splitMeshEdge(mesh,pair,fraction=.5){if(!Number.isFinite(fraction)||fraction<=0||fraction>=1)throw new Error('Punkt musi leżeć wewnątrz krawędzi.');const next=structuredClone(mesh),a=next.vertices[pair[0]],b=next.vertices[pair[1]],length=Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);if(Math.min(fraction,1-fraction)*length<.002)throw new Error('Punkt musi być co najmniej 0,2 cm od końca krawędzi.');const id=next.vertices.length;next.vertices.push({x:a.x+(b.x-a.x)*fraction,y:a.y+(b.y-a.y)*fraction,z:a.z+(b.z-a.z)*fraction});for(const face of next.faces){const list=[];for(let i=0;i<face.indices.length;i++){const x=face.indices[i],y=face.indices[(i+1)%face.indices.length];list.push(x);if(pair.includes(x)&&pair.includes(y))list.push(id);}face.indices=list;}return normalizeRoomMesh(next);}

export function meshPlanOperation(mesh,kind,ids,width,depth){const floor=mesh.faces.find(f=>f.id==='floor'),ceiling=mesh.faces.find(f=>f.id==='ceiling');if(!floor||!ceiling)throw new Error('Ta operacja wymaga pod�ogi i sufitu.');const points=floor.indices.map(i=>mesh.vertices[i]),bottom=points[0].y,top=mesh.vertices[ceiling.indices[0]].y;if(points.some(p=>Math.abs(p.y-bottom)>1e-6)||ceiling.indices.some(i=>Math.abs(mesh.vertices[i].y-top)>1e-6)||mesh.vertices.some(p=>!points.some(q=>Math.hypot(q.x-p.x,q.z-p.z)<1e-6)))throw new Error('Wn�ki i skosy obrysu wymagaj� pionowych �cian i poziomej pod�ogi.');const target=mesh.vertices[ids[0]],index=points.findIndex(p=>Math.hypot(p.x-target.x,p.z-target.z)<1e-6);let edge=index;if(kind==='recess'){const b=mesh.vertices[ids[1]];if(Math.abs(b.y-target.y)>1e-6)throw new Error('Wybierz poziomą krawędź.');if(Math.hypot(points[(index+1)%points.length].x-b.x,points[(index+1)%points.length].z-b.z)>1e-6)edge=(index+points.length-1)%points.length;}const outline=points.map(p=>({x:p.x,z:p.z})),next=kind==='recess'?recessEdge(outline,edge,width,depth):bevelVertex(outline,index,width),roof=mesh.faces.find(f=>f.id==='niche-roof');
 let result;
 if(roof){const first=mesh.vertices[roof.indices.at(-1)],last=mesh.vertices[roof.indices[0]],find=p=>next.findIndex(q=>Math.hypot(q.x-p.x,q.z-p.z)<1e-6),left=find(first),right=find(last);if(left<0||right<=left)throw new Error('Zmiana usuwa narożnik wnęki; najpierw edytuj jej krawędzie bezpośrednio.');result=partialNicheMesh(next,top-bottom,first.y-bottom,left,right);}
 else result=initialRoomMesh({room:{height:top-bottom},roomShape:next});
 result.vertices.forEach(p=>p.y+=bottom);return normalizeRoomMesh(result);}
