import * as THREE from 'three';
import {normalizeFootprint} from './surface-model.js';
import {WALL_PAINT_COLOR} from './wall-paint.js';
import {applyFolignoFloor} from './floor-finish.js';
export function createFootprintRoom(room,input,features){const points=normalizeFootprint(input),group=new THREE.Group(),surfaces=[],materials=[],geometries=[];group.name='room';
 const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minZ=Math.min(...points.map(p=>p.z)),maxZ=Math.max(...points.map(p=>p.z));
 function add(name,geometry,position,rotation,normal,color){const material=new THREE.MeshStandardMaterial({color,side:THREE.DoubleSide,roughness:0.9}),mesh=new THREE.Mesh(geometry,material);materials.push(material);geometries.push(geometry);mesh.name=name;mesh.position.copy(position);mesh.quaternion.copy(rotation);mesh.userData.outward=normal;if(name==='floor')applyFolignoFloor(mesh);group.add(mesh);surfaces.push(mesh);return mesh;}
 for(const [name,y,sign,color] of [['floor',0,-1,0x4c6572],['ceiling',room.height,1,0xadc1c9]]){const shape=new THREE.Shape();const coords=points.map(p=>[p.x-(minX+maxX)/2,sign*(p.z-(minZ+maxZ)/2)]);shape.moveTo(...coords[0]);for(const p of coords.slice(1))shape.lineTo(...p);shape.closePath();const geometry=new THREE.ShapeGeometry(shape);geometry.parameters.width=maxX-minX;geometry.parameters.height=maxZ-minZ;add(name,geometry,new THREE.Vector3((minX+maxX)/2,y,(minZ+maxZ)/2),new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),sign*Math.PI/2),new THREE.Vector3(0,sign,0),color);}
 const counts={};for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],dx=b.x-a.x,dz=b.z-a.z,length=Math.hypot(dx,dz),normal=new THREE.Vector3(dz/length,0,-dx/length);let base=Math.abs(a.z)<1e-7&&Math.abs(b.z)<1e-7?'wall-front':Math.abs(a.z-room.length)<1e-7&&Math.abs(b.z-room.length)<1e-7?'wall-back':Math.abs(a.x)<1e-7&&Math.abs(b.x)<1e-7?'wall-left':Math.abs(a.x-room.width)<1e-7&&Math.abs(b.x-room.width)<1e-7?'wall-right':'wall-edge-'+i;counts[base]=(counts[base]??0)+1;const name=counts[base]===1?base:base+'-'+counts[base];let geometry=new THREE.PlaneGeometry(length,room.height);
  if(base==='wall-back'&&dx<0&&features?.door){const d=features.door,left=d.center-d.width/2-(a.x+b.x)/2,right=left+d.width;if(left>-length/2&&right<length/2){const shape=new THREE.Shape();shape.moveTo(-length/2,-room.height/2);shape.lineTo(left,-room.height/2);shape.lineTo(left,d.height-room.height/2);shape.lineTo(right,d.height-room.height/2);shape.lineTo(right,-room.height/2);shape.lineTo(length/2,-room.height/2);shape.lineTo(length/2,room.height/2);shape.lineTo(-length/2,room.height/2);shape.closePath();geometry.dispose();geometry=new THREE.ShapeGeometry(shape);geometry.parameters.width=length;geometry.parameters.height=room.height;}}
  const mesh=add(name,geometry,new THREE.Vector3((a.x+b.x)/2,room.height/2,(a.z+b.z)/2),new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),normal),normal,WALL_PAINT_COLOR);mesh.userData.edgeIndex=i;
 }
 const lines=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];lines.push(a.x,0.002,a.z,b.x,0.002,b.z);}const lineMaterial=new THREE.LineBasicMaterial({color:0xa6cbd5}),lineGeometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(lines,3)),outline=new THREE.LineSegments(lineGeometry,lineMaterial);outline.name='floor-outline';group.add(outline);materials.push(lineMaterial);geometries.push(lineGeometry);const gridPoints=[];
 for(const axis of ['x','z']){const other=axis==='x'?'z':'x',low=axis==='x'?minX:minZ,high=axis==='x'?maxX:maxZ;
  for(let value=Math.ceil(low*10)/10;value<high;value+=0.1){const intersections=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];if((a[axis]<=value&&b[axis]>value)||(b[axis]<=value&&a[axis]>value))intersections.push(a[other]+(b[other]-a[other])*(value-a[axis])/(b[axis]-a[axis]));}intersections.sort((a,b)=>a-b);for(let i=0;i+1<intersections.length;i+=2){for(const v of [intersections[i],intersections[i+1]])gridPoints.push(axis==='x'?value:v,0.002,axis==='z'?value:v);}}
 }
 const gridGeometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(gridPoints,3)),gridMaterial=new THREE.LineBasicMaterial({color:0x9bb7c3,transparent:true,opacity:0.25}),grid=new THREE.LineSegments(gridGeometry,gridMaterial);grid.name='floor-grid';group.add(grid);materials.push(gridMaterial);geometries.push(gridGeometry);
 return {group,surfaces,grid,updateVisibility(camera,cutaway){for(const s of surfaces){const facing=s.userData.outward.dot(camera.position.clone().sub(s.position));s.visible=!!s.userData.monitorCollision||!cutaway||s.name==='floor'||(s.name!=='ceiling'&&facing<=0);}},dispose(){for(const g of geometries)g.dispose();for(const m of materials)m.dispose();}};
}
