export function initialFootprint(doc){const {width:w,length:l}=doc.room,n=doc.roomFeatures.window,t=doc.transforms.window??{},left=Math.max(0,n.center+(t.x??0)-n.width/2),right=Math.min(w,n.center+(t.x??0)+n.width/2);if(n.bottom+(t.y??0)>0.001||right<=left)return [{x:0,z:0},{x:w,z:0},{x:w,z:l},{x:0,z:l}];const p=[{x:0,z:0},{x:left,z:0},{x:left,z:-n.depth},{x:right,z:-n.depth},{x:right,z:0},{x:w,z:0},{x:w,z:l},{x:0,z:l}];return p.filter((a,i)=>i===0||Math.hypot(a.x-p[i-1].x,a.z-p[i-1].z)>=.002);}
const cross=(a,b,c)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);
export function footprintArea(points){return Math.abs(points.reduce((sum,p,i)=>{const q=points[(i+1)%points.length];return sum+p.x*q.z-q.x*p.z;},0))/2;}
export function normalizeFootprint(points){if(points==null)return null;if(!Array.isArray(points)||points.length<3||points.length>128)throw new Error('Obrys musi mieć od 3 do 128 wierzchołków.');const p=points.map(v=>{if(!v||![v.x,v.z].every(Number.isFinite)||Math.abs(v.x)>100||Math.abs(v.z)>100)throw new Error('Nieprawidłowy wierzchołek.');return {x:v.x,z:v.z};});
 for(let i=0;i<p.length;i++){const a=p[(i+p.length-1)%p.length],b=p[i],c=p[(i+1)%p.length];if(Math.abs(cross(a,b,c))<1e-9&&(a.x-b.x)*(c.x-b.x)+(a.z-b.z)*(c.z-b.z)>0)throw new Error('Kraw�dzie nie mog� nak�ada� si� na siebie.');}
 const on=(a,b,c)=>Math.abs(cross(a,b,c))<1e-9&&c.x>=Math.min(a.x,b.x)-1e-9&&c.x<=Math.max(a.x,b.x)+1e-9&&c.z>=Math.min(a.z,b.z)-1e-9&&c.z<=Math.max(a.z,b.z)+1e-9;
 for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];if(Math.hypot(a.x-b.x,a.z-b.z)<0.002)throw new Error('Krawędź jest zbyt krótka.');for(let j=i+1;j<p.length;j++){if(j===i+1||(i===0&&j===p.length-1))continue;const c=p[j],d=p[(j+1)%p.length];if((cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0)||on(a,b,c)||on(a,b,d)||on(c,d,a)||on(c,d,b))throw new Error('Krawędzie obrysu nie mogą się przecinać.');}}
 if(footprintArea(p)<0.01)throw new Error('Powierzchnia jest zbyt mała.');const signed=p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+a.x*b.z-b.x*a.z;},0);return signed<0?p.reverse():p;}
export function splitEdge(points,index){const p=structuredClone(points),a=p[index],b=p[(index+1)%p.length];p.splice(index+1,0,{x:(a.x+b.x)/2,z:(a.z+b.z)/2});return normalizeFootprint(p);}
export function recessEdge(points,index,width,depth){const p=structuredClone(points),a=p[index],b=p[(index+1)%p.length],dx=b.x-a.x,dz=b.z-a.z,length=Math.hypot(dx,dz);if(!Number.isFinite(width)||!Number.isFinite(depth)||width<=0||width>=length-0.004||Math.abs(depth)<0.002)throw new Error('Wnęka musi być węższa od krawędzi i mieć głębokość co najmniej 0,2 cm.');const start=(length-width)/2,lengthRatio=start/length,end=(start+width)/length,normal={x:dz/length,z:-dx/length},A={x:a.x+dx*lengthRatio,z:a.z+dz*lengthRatio},B={x:a.x+dx*end,z:a.z+dz*end};p.splice(index+1,0,A,{x:A.x+normal.x*depth,z:A.z+normal.z*depth},{x:B.x+normal.x*depth,z:B.z+normal.z*depth},B);return normalizeFootprint(p);}
export function bevelVertex(points,index,size){const p=structuredClone(points),v=p[index],a=p[(index+p.length-1)%p.length],b=p[(index+1)%p.length],la=Math.hypot(v.x-a.x,v.z-a.z),lb=Math.hypot(v.x-b.x,v.z-b.z);if(!Number.isFinite(size)||size<=0||size>=Math.min(la,lb)-0.002)throw new Error('Skos jest zbyt duży dla tych krawędzi.');p.splice(index,1,{x:v.x+(a.x-v.x)*size/la,z:v.z+(a.z-v.z)*size/la},{x:v.x+(b.x-v.x)*size/lb,z:v.z+(b.z-v.z)*size/lb});return normalizeFootprint(p);}
export function dissolveSelection(points,indices,mode){const remove=new Set([...indices].map(i=>mode==='edge'?(i+1)%points.length:i));return normalizeFootprint(points.filter((_,i)=>!remove.has(i)));}
