import {normalizeFootprint,splitEdge,recessEdge,bevelVertex,dissolveSelection} from './surface-model.js';
export function setupSurfacePanel({read,change,showError}){const $=id=>document.getElementById(id),svg=$('shape-canvas'),NS='http://www.w3.org/2000/svg';let mode='vertex',selection=new Set(),drag=null,frame;
 const node=(tag,attributes,parent=svg)=>{const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attributes))n.setAttribute(k,v);parent.append(n);return n;};
 function render(){const p=read();if(!p)return;selection=new Set([...selection].filter(i=>i<p.length));const minX=Math.min(...p.map(p=>p.x)),maxX=Math.max(...p.map(p=>p.x)),minZ=Math.min(...p.map(p=>p.z)),maxZ=Math.max(...p.map(p=>p.z));frame=drag?.frame??{minX,minZ,scale:Math.min(230/(maxX-minX),250/(maxZ-minZ))};const screen=p=>({x:25+(p.x-frame.minX)*frame.scale,y:25+(p.z-frame.minZ)*frame.scale});svg.replaceChildren();node('polygon',{points:p.map(screen).map(p=>p.x+','+p.y).join(' '),fill:'#22343c',stroke:'none'});
  for(let i=0;i<p.length;i++){const a=screen(p[i]),b=screen(p[(i+1)%p.length]);node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:mode==='edge'&&selection.has(i)?'#ffdc72':'#80b6c4','stroke-width':mode==='edge'&&selection.has(i)?4:2});if(mode==='edge')node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'transparent','stroke-width':14,'data-index':i,'data-kind':'edge'});}
  for(let i=0;i<p.length;i++){const a=screen(p[i]);node('circle',{cx:a.x,cy:a.y,r:mode==='vertex'?6:3,fill:mode==='vertex'&&selection.has(i)?'#ffdc72':'#74dcc2','data-index':i,'data-kind':'vertex'});}
  if(drag?.marquee){const a=drag.origin,b=drag.last;node('rect',{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y),fill:'#74dcc222',stroke:'#74dcc2','stroke-dasharray':'4 3','pointer-events':'none'});}
  $('shape-count').textContent=p.length+' wierzchołków · zaznaczone: '+selection.size;$('shape-vertex-mode').classList.toggle('active',mode==='vertex');$('shape-edge-mode').classList.toggle('active',mode==='edge');
 }
 const pointer=e=>{const r=svg.getBoundingClientRect();return {x:(e.clientX-r.left)*280/r.width,y:(e.clientY-r.top)*300/r.height};};
 svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;svg.focus();const index=e.target.getAttribute('data-index'),kind=e.target.getAttribute('data-kind'),origin=pointer(e),start=structuredClone(read());if(index!==null&&kind===mode){const i=Number(index);if(e.ctrlKey){if(selection.has(i))selection.delete(i);else selection.add(i);}else if(!selection.has(i))selection=new Set([i]);const vertices=new Set([...selection].flatMap(i=>mode==='vertex'?[i]:[i,(i+1)%start.length]));drag={origin,start,vertices,frame:{...frame},marquee:false,changed:false};}else{if(!e.ctrlKey)selection.clear();drag={origin,last:origin,start,frame:{...frame},marquee:true,base:new Set(selection)};}svg.setPointerCapture(e.pointerId);drag.id=e.pointerId;render();});
 svg.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;const pos=pointer(e);drag.last=pos;if(drag.marquee){const lowX=Math.min(pos.x,drag.origin.x),highX=Math.max(pos.x,drag.origin.x),lowY=Math.min(pos.y,drag.origin.y),highY=Math.max(pos.y,drag.origin.y);selection=new Set(drag.base);drag.start.forEach((p,i)=>{const q=mode==='vertex'?p:{x:(p.x+drag.start[(i+1)%drag.start.length].x)/2,z:(p.z+drag.start[(i+1)%drag.start.length].z)/2},x=25+(q.x-drag.frame.minX)*drag.frame.scale,y=25+(q.z-drag.frame.minZ)*drag.frame.scale;if(x>=lowX&&x<=highX&&y>=lowY&&y<=highY)selection.add(i);});render();return;}let dx=(pos.x-drag.origin.x)/drag.frame.scale,dz=(pos.y-drag.origin.y)/drag.frame.scale;if(e.shiftKey){if(Math.abs(dx)>Math.abs(dz))dz=0;else dx=0;}const next=drag.start.map((p,i)=>drag.vertices.has(i)?{x:p.x+dx,z:p.z+dz}:p);try{change(normalizeFootprint(next),false);drag.changed=true;render();}catch(error){showError(error);}});
 function finish(e){if(drag?.id!==e.pointerId)return;const was=drag;drag=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);if(was.changed)change(read(),true);render();}
 svg.addEventListener('pointerup',finish);svg.addEventListener('lostpointercapture',e=>{if(drag?.id===e.pointerId){const start=drag.start;drag=null;change(start,false);render();}});svg.addEventListener('pointercancel',()=>{if(drag&&!drag.marquee)change(drag.start,false);drag=null;render();});
 function action(operation){try{if(!selection.size)throw new Error('Zaznacz wierzchołek lub krawędź.');change(operation(structuredClone(read()),[...selection]),true);selection.clear();render();}catch(error){showError(error);}}
 $('shape-vertex-mode').onclick=()=>{mode='vertex';selection.clear();render();};$('shape-edge-mode').onclick=()=>{mode='edge';selection.clear();render();};
 $('shape-split').onclick=()=>{if(mode!=='edge'){showError(new Error('Wybierz tryb krawędzi.'));return;}action((p,s)=>splitEdge(p,s[0]));};
 $('shape-recess').onclick=()=>{if(mode!=='edge'){showError(new Error('Wybierz krawędź dla wnęki.'));return;}action((p,s)=>recessEdge(p,s[0],Number($('shape-width').value)/100,Number($('shape-depth').value)/100));};
 $('shape-bevel').onclick=()=>{if(mode!=='vertex'){showError(new Error('Wybierz wierzchołek narożnika.'));return;}action((p,s)=>bevelVertex(p,s[0],Number($('shape-bevel-size').value)/100));};
 const remove=()=>action((p,s)=>dissolveSelection(p,s,mode));$('shape-delete').onclick=remove;
 svg.addEventListener('keydown',e=>{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}if(e.key==='Escape'&&drag){const start=drag.start;drag=null;change(start,false);render();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selection=new Set(read().map((_,i)=>i));render();}});
 return {pick(surface){let index=surface?.userData.edgeIndex;if(index===undefined&&surface?.name.startsWith('wall-')){const p=read(),n=surface.userData.outward;index=p.findIndex((a,i)=>{const b=p[(i+1)%p.length],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz);return Math.abs((dz*n.x-dx*n.z)/len-1)<1e-6&&Math.abs((a.x-surface.position.x)*n.x+(a.z-surface.position.z)*n.z)<1e-6;});}if(index!==undefined&&index>=0){mode='edge';selection=new Set([index]);}render();},sync(surface){$('shape-surface').textContent=surface?.name==='floor'?'Podłoga':surface?.name==='ceiling'?'Sufit':surface?'Ściana':'Obrys pokoju';render();}};
}
