import {setupAxisGizmo} from './axis-gizmo.js';
import * as THREE from 'three';

import {meshEdges,transformMesh,dissolveMesh,splitMeshEdge,meshPlanOperation} from './mesh-model.js';

export function setupViewportEditor({host,read,camera,controls,change,selectSurface,visibleIds,showError}){const $=id=>document.getElementById(id),svg=$('edit-overlay'),popup=$('edit-popup');let pivot=null;let showAll=false;let enabled=true,mode='vertex',selection=new Set(),face=null,base=null,drag=null,signature='';const node=(tag,attrs)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;};

function indices(){const mesh=read();if(mode==='face')return mesh.faces.find(f=>f.id===face)?.indices??[];if(mode==='edge')return [...new Set([...selection].flatMap(i=>meshEdges(mesh)[i]??[]))];return [...selection];}

function center(mesh=read(),ids=indices()){return ids.reduce((p,i)=>p.add(new THREE.Vector3(mesh.vertices[i].x,mesh.vertices[i].y,mesh.vertices[i].z)),new THREE.Vector3()).multiplyScalar(1/(ids.length||1));}

let gizmo;
function syncFields(preserveAxis=false){base=structuredClone(read());const ids=indices();popup.hidden=true;$('edit-title').textContent=mode==='face'?'Powierzchnia':mode==='edge'?'Krawędzie':'Wierzchołki';const p=center();for(const k of ['x','y','z']){$('edit-p-'+k).value=(p[k]*100).toFixed(1);$('edit-r-'+k).value='0';$('edit-r-'+k).disabled=ids.length<2;}$('edit-remove').disabled=mode==='face';$('edit-split').disabled=mode!=='edge'||selection.size!==1;host.dataset.meshSelection=ids.join(',');if(preserveAxis)gizmo?.sync(ids);else gizmo?.reset(ids);}

function render(){gizmo?.render();if(!enabled){svg.replaceChildren();return;}const mesh=read(),cam=camera(),width=host.clientWidth,height=host.clientHeight;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);const shown=visibleIds?.(),projected=mesh.vertices.map((p,i)=>{const v=new THREE.Vector3(p.x,p.y,p.z).project(cam);return {x:(v.x+1)*width/2,y:(1-v.y)*height/2,visible:v.z>=-1&&v.z<=1&&(!shown||shown.includes(i))};}),key=JSON.stringify([projected,showAll,mode,[...selection],face,pivot,drag?.last]);if(key===signature)return;signature=key;svg.replaceChildren();for(const [i,pair] of meshEdges(mesh).entries()){const [a,b]=pair.map(i=>projected[i]);if(!a.visible||!b.visible)continue;if(showAll||(mode==='edge'&&selection.has(i)))node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:mode==='edge'&&selection.has(i)?'#ffdc72':'#80b6c4','stroke-width':mode==='edge'&&selection.has(i)?4:1.5,'pointer-events':'none'});node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'transparent','stroke-width':15,'data-index':i,'data-kind':'edge','pointer-events':'stroke'});}projected.forEach((p,i)=>{if(p.visible)node('circle',{cx:p.x,cy:p.y,r:mode==='vertex'&&selection.has(i)?7:5,fill:mode==='vertex'&&selection.has(i)?'#ffdc72':showAll?'#74dcc2':'transparent','data-index':i,'data-kind':'vertex','pointer-events':'all'});});if(pivot){const v=new THREE.Vector3(pivot.position.x,pivot.position.y,pivot.position.z).project(cam);if(v.z>=-1&&v.z<=1)node('circle',{cx:(v.x+1)*width/2,cy:(1-v.y)*height/2,r:11,fill:'none',stroke:'#74dcc2','stroke-width':2,'pointer-events':'none','data-pivot':'true'});}if(drag?.marquee){const a=drag.start,b=drag.last;node('rect',{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y),fill:'#74dcc222',stroke:'#74dcc2','pointer-events':'none'});}return projected;}

function clear(){pivot=null;host.dataset.rotationPivot='';gizmo?.clear();const before=drag;drag=null;if(before&&!before.marquee&&!before.camera)change(before.base,false);controls().enabled=true;selection.clear();face=null;selectSurface(null);syncFields();signature='';render();}
function updateCaps(event){if(typeof event.getModifierState!=='function')return;const next=event.getModifierState('CapsLock');if(next!==showAll){showAll=next;signature='';render();}host.dataset.allGeometryHandles=String(showAll);}
document.addEventListener('keydown',updateCaps,true);document.addEventListener('keyup',updateCaps,true);host.addEventListener('pointerdown',updateCaps,true);host.addEventListener('pointermove',updateCaps,true);
$('edit-tools').hidden=true;svg.removeAttribute('hidden');host.dataset.meshEditing='direct';$('edit-popup-close').onclick=clear;
for(const k of ['x','y','z'])for(const prefix of ['p','r'])$('edit-'+prefix+'-'+k).addEventListener('input',()=>{try{const position={},rotation={};for(const axis of ['x','y','z']){const p=$('edit-p-'+axis),r=$('edit-r-'+axis);if(p.value===''||r.value==='')return;position[axis]=Number(p.value)/100;rotation[axis]=Number(r.value);}change(transformMesh(base,indices(),position,rotation),false);signature='';}catch(e){showError(e);}});

for(const input of popup.querySelectorAll('[id^=edit-p-],[id^=edit-r-]'))input.addEventListener('change',()=>{change(read(),true);});

$('edit-remove').onclick=()=>{try{change(dissolveMesh(read(),mode==='edge'?[...selection].map(i=>meshEdges(read())[i][1]):indices()),true);selection.clear();syncFields();signature='';}catch(e){showError(e);}};

$('edit-split').onclick=()=>{try{change(splitMeshEdge(read(),meshEdges(read())[[...selection][0]]),true);selection.clear();syncFields();signature='';}catch(e){showError(e);}};

const pos=e=>{const r=host.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};

host.addEventListener('pointerdown',e=>{if(!enabled||e.button!==0||e.target.closest('button,input,label,#edit-popup,#edit-tools,#axis-gizmo,.view-tools,#distance-label'))return;const index=e.target.getAttribute?.('data-index');if(index==null&&!e.ctrlKey)return;e.preventDefault();e.stopImmediatePropagation();const start=pos(e);if(index!=null){const kind=e.target.getAttribute('data-kind'),i=Number(index),wasSelected=mode===kind&&selection.has(i)&&!e.ctrlKey;if(e.shiftKey&&kind==='vertex'&&indices().length){pivot={index:i,position:{...read().vertices[i]}};host.dataset.rotationPivot=String(i);gizmo?.pivotChanged();signature='';render();return;}if(!wasSelected){pivot=null;host.dataset.rotationPivot='';}if(mode!==kind){selection.clear();mode=kind;}face=null;selectSurface(null);if(e.ctrlKey){if(selection.has(i))selection.delete(i);else selection.add(i);}else if(!selection.has(i))selection=new Set([i]);syncFields();if(!wasSelected){drag={id:e.pointerId,start,last:start,camera:true,position:camera().position.clone(),target:controls().target.clone()};controls().enabled=false;if(e.isTrusted)host.setPointerCapture(e.pointerId);signature='';render();return;}const point=center(),plane=new THREE.Plane().setFromNormalAndCoplanarPoint(camera().getWorldDirection(new THREE.Vector3()),point);drag={id:e.pointerId,start,last:start,plane,origin:point,base:structuredClone(read()),ids:indices(),changed:false};}else{if(mode==='face'){mode='vertex';selection.clear();face=null;selectSurface(null);}if(!e.ctrlKey)selection.clear();drag={id:e.pointerId,start,last:start,marquee:true,baseSelection:new Set(selection)};}controls().enabled=false;if(e.isTrusted)host.setPointerCapture(e.pointerId);signature='';render();},true);

host.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;drag.last=pos(e);if(drag.camera){const r=host.getBoundingClientRect(),offset=drag.position.clone().sub(drag.target),spherical=new THREE.Spherical().setFromVector3(offset);spherical.theta-=((drag.last.x-drag.start.x)/r.height)*Math.PI*2;spherical.phi=Math.max(.001,Math.min(Math.PI-.001,spherical.phi-((drag.last.y-drag.start.y)/r.height)*Math.PI*2));camera().position.copy(drag.target).add(new THREE.Vector3().setFromSpherical(spherical));camera().lookAt(drag.target);controls().update();}else if(drag.marquee){const mesh=read(),r=host.getBoundingClientRect(),project=p=>{const v=new THREE.Vector3(p.x,p.y,p.z).project(camera());return {x:(v.x+1)*r.width/2,y:(1-v.y)*r.height/2};},points=mode==='vertex'?mesh.vertices:meshEdges(mesh).map(([a,b])=>({x:(mesh.vertices[a].x+mesh.vertices[b].x)/2,y:(mesh.vertices[a].y+mesh.vertices[b].y)/2,z:(mesh.vertices[a].z+mesh.vertices[b].z)/2}));selection=new Set(drag.baseSelection);points.forEach((p,i)=>{const q=project(p);if(q.x>=Math.min(drag.start.x,drag.last.x)&&q.x<=Math.max(drag.start.x,drag.last.x)&&q.y>=Math.min(drag.start.y,drag.last.y)&&q.y<=Math.max(drag.start.y,drag.last.y))selection.add(i);});}else{const r=host.getBoundingClientRect(),ray=new THREE.Raycaster(),hit=p=>{ray.setFromCamera(new THREE.Vector2(p.x/r.width*2-1,1-p.y/r.height*2),camera());return ray.ray.intersectPlane(drag.plane,new THREE.Vector3());},a=hit(drag.start),b=hit(drag.last);if(a&&b){let delta=b.sub(a);if(e.shiftKey){const axis=['x','y','z'].sort((a,b)=>Math.abs(delta[b])-Math.abs(delta[a]))[0];for(const k of ['x','y','z'])if(k!==axis)delta[k]=0;}try{const target=drag.origin.clone().add(delta);change(transformMesh(drag.base,drag.ids,target,{x:0,y:0,z:0}),false);drag.changed=true;}catch(error){showError(error);}}}signature='';render();},true);

host.addEventListener('pointerup',e=>{if(drag?.id!==e.pointerId)return;e.stopImmediatePropagation();const before=drag;drag=null;controls().enabled=true;if(host.hasPointerCapture(e.pointerId))host.releasePointerCapture(e.pointerId);if(before.changed)change(read(),true);if(before.camera)controls().update();syncFields();signature='';render();},true);

host.addEventListener('pointercancel',()=>{if(drag){const before=drag;drag=null;if(!before.marquee&&!before.camera)change(before.base,false);controls().enabled=true;syncFields();}});

document.addEventListener('keydown',e=>{if(e.key==='Escape'){clear();return;}if(e.target.matches('input,textarea'))return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();$('edit-remove').click();}});
gizmo=setupAxisGizmo({read,camera,controls,change,readPivot:()=>pivot?.position??null,refresh(){base=structuredClone(read());const p=center();for(const k of ['x','y','z'])$('edit-p-'+k).value=(p[k]*100).toFixed(1);signature='';},showError});
$('edit-recess').onclick=()=>{try{if(mode!=='edge'||selection.size!==1)throw new Error('Zaznacz jedn� poziom� kraw�d�.');change(meshPlanOperation(read(),'recess',meshEdges(read())[[...selection][0]],Number($('edit-width').value)/100,Number($('edit-depth').value)/100),true);selection.clear();syncFields();signature='';}catch(e){showError(e);}};$('edit-bevel').onclick=()=>{try{if(mode!=='vertex'||selection.size!==1)throw new Error('Zaznacz jeden naro�nik.');change(meshPlanOperation(read(),'bevel',indices(),Number($('edit-bevel-size').value)/100,0),true);selection.clear();syncFields();signature='';}catch(e){showError(e);}};return {get faceId(){return face;},clear,render,get enabled(){return enabled;},pick(surface){if(surface){pivot=null;host.dataset.rotationPivot='';mode='face';face=surface.name;const mesh=read();if(!mesh.faces.some(f=>f.id===face)){const n=surface.userData.outward;face=mesh.faces.find(f=>f.indices.every(i=>{const p=mesh.vertices[i];return Math.abs((p.x-surface.position.x)*n.x+(p.y-surface.position.y)*n.y+(p.z-surface.position.z)*n.z)<1e-6;}))?.id;}selection.clear();selectSurface(surface);syncFields();signature='';}},capture(){return {ids:indices(),pivot:structuredClone(pivot),base:structuredClone(base),gizmo:gizmo.capture(),rotation:['x','y','z'].map(k=>$('edit-r-'+k).value)};},restore(state){if(JSON.stringify(state.ids)!==JSON.stringify(indices()))return;pivot=structuredClone(state.pivot??null);host.dataset.rotationPivot=pivot?String(pivot.index):'';base=structuredClone(state.base);gizmo.restore(state.gizmo);['x','y','z'].forEach((k,i)=>$('edit-r-'+k).value=state.rotation[i]);},sync(force=false){signature='';if(force||(!drag&&!gizmo.active&&document.activeElement?.closest('#edit-popup')==null))syncFields(force);}};

}

