import test from 'node:test';import assert from 'node:assert/strict';import {initialRoomMesh} from './src/mesh-model.js';import {createDocument} from './src/model.js';import {moveAlongAxis,movementDirection,axisDragDistance,parseDisplacement} from './src/axis-move.js';
test('centimeter movement applies only to selected vertices on specified world axis',()=>{const mesh=initialRoomMesh(createDocument());for(const ids of [[0],[0,1],mesh.faces[2].indices])for(const axis of ['x','y','z']){const changed=moveAlongAxis(mesh,ids,axis,12.5);mesh.vertices.forEach((p,i)=>{for(const k of ['x','y','z'])assert.ok(Math.abs(changed.vertices[i][k]-p[k]-(ids.includes(i)&&k===axis?.125:0))<1e-8);});}});
test('typing replaces drag displacement relative to gesture start and supports signed Polish decimals',()=>{const mesh=initialRoomMesh(createDocument()),drag=moveAlongAxis(mesh,[0],'x',20),typed=moveAlongAxis(mesh,[0],'x',parseDisplacement('-5,5'));assert.equal(drag.vertices[0].x,.2);assert.equal(typed.vertices[0].x,-.055);for(const s of ['','-','foo','1,2,3'])assert.equal(parseDisplacement(s),null);assert.equal(axisDragDistance({x:0,y:0},{x:30,y:40},{x:1,y:0}),30);assert.equal(axisDragDistance({x:0,y:0},{x:30,y:40},{x:0,y:0}),-40);});

test('diagonal displacement has equal X/Z components, correct total length and preserves height',()=>{const mesh=initialRoomMesh(createDocument()),ids=[0,1],changed=moveAlongAxis(mesh,ids,'direction',-25);mesh.vertices.forEach((v,i)=>{const d=changed.vertices[i];assert.equal(d.y,v.y);const step=ids.includes(i)?-.25*Math.SQRT1_2:0;assert.ok(Math.abs(d.x-v.x-step)<1e-8);assert.ok(Math.abs(d.z-v.z-step)<1e-8);if(ids.includes(i))assert.ok(Math.abs(Math.hypot(d.x-v.x,d.z-v.z)-.25)<1e-8);});});

test('XZ and YZ rotation directions compose without changing scale and support full turns',()=>{const base=movementDirection('direction'),xz=movementDirection('direction',{xz:90}),yz=movementDirection('direction',{yz:90});assert.ok(Math.abs(xz.x+base.z)<1e-8);assert.ok(Math.abs(xz.z-base.x)<1e-8);assert.ok(Math.abs(yz.y+base.z)<1e-8);assert.ok(Math.abs(yz.z)<1e-8);for(const plane of ['xy','xz','yz'])assert.ok(movementDirection('direction',{[plane]:360}).distanceTo(base)<1e-8);assert.ok(Math.abs(movementDirection('direction',{xy:20,xz:30,yz:40}).length()-1)<1e-8);});

test('yellow direction aligns with chosen base axis and rotations use the chosen axis',()=>{for(const baseAxis of ['x','y','z'])assert.ok(movementDirection('direction',{baseAxis}).distanceTo(movementDirection(baseAxis))<1e-8);assert.ok(movementDirection('direction',{baseAxis:'x',xy:90}).distanceTo(movementDirection('y'))<1e-8);assert.ok(movementDirection('direction',{baseAxis:'y',yz:90}).distanceTo(movementDirection('z'))<1e-8);});
