import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createDocument} from './src/model.js';
import {createRoom} from './src/room-view.js';
import {createSeatedListener} from './src/listener-view.js';
import {createStudioMonitor} from './src/monitor-view.js';
import {findMonitorCollisions,tintCollision} from './src/monitor-collisions.js';
import {createRoomFeatureViews} from './src/room-features.js';
function fixture(){const doc=createDocument(),listener=createSeatedListener(doc.objects[0]),monitors=doc.objects.filter(o=>o.type==='studio-monitor').map(createStudioMonitor);return {doc,listener,monitors,check(objects=[listener.group,...monitors.map(m=>m.group)]){return findMonitorCollisions(monitors,objects,doc.room);},dispose(){listener.dispose();monitors.forEach(m=>m.dispose());}};}
test('default placement is clear; rotated full monitor envelope crosses correct wall; contact alone is clear',()=>{const f=fixture();assert.equal(f.check().surfaces.size,0);assert.equal(f.check().targets.size,0);const m=f.monitors[0].group;m.rotation.y=0;m.position.x=0.1335;assert.equal(f.check().surfaces.size,0);m.position.x=0.20;assert.equal(f.check().surfaces.size,0);m.rotation.y=Math.PI/4;assert.ok(f.check().surfaces.has('wall-left'));m.position.x=0.7;assert.equal(f.check().surfaces.size,0);f.dispose();});
test('all six room boundaries report penetration',()=>{const f=fixture(),m=f.monitors[0].group;m.rotation.y=0;for(const [name,position] of [['wall-left',[-0.01,0.9,0.65]],['wall-right',[f.doc.room.width,0.9,0.65]],['wall-front',[0.7,0.9,0.1]],['wall-back',[0.7,0.9,f.doc.room.length-0.1]],['floor',[0.7,-0.01,0.65]],['ceiling',[0.7,f.doc.room.height-0.5,0.65]]]){m.position.set(...position);assert.ok(f.check().surfaces.has(name),name);}f.dispose();});
test('monitor hits human mesh and another monitor; does not count helpers or empty space',()=>{const f=fixture(),m=f.monitors[0].group,head=f.listener.group.getObjectByName('head').getWorldPosition(new THREE.Vector3());m.position.copy(head).add(new THREE.Vector3(0,-0.26,0));m.rotation.y=0;assert.ok(f.check().targets.has(f.listener.group));m.position.set(0.3,1.5,2.8);assert.equal(f.check().targets.has(f.listener.group),false);f.monitors[1].group.position.copy(m.position);f.monitors[1].group.rotation.y=0;const result=f.check();assert.ok(result.targets.has(m));assert.ok(result.targets.has(f.monitors[1].group));f.dispose();});
test('generic future object and monitor fully enclosed in object are detected',()=>{const f=fixture(),object=new THREE.Group(),mesh=new THREE.Mesh(new THREE.BoxGeometry(0.3,0.6,0.5),new THREE.MeshStandardMaterial({color:0x123456}));object.add(mesh);const m=f.monitors[0].group;m.rotation.y=0;m.position.set(0.7,0.7,2.7);object.position.set(0.7,0.96,2.7);assert.ok(f.check([object]).targets.has(object));mesh.scale.set(3,3,3);assert.ok(f.check([object]).targets.has(object));mesh.userData.collision=false;assert.equal(f.check([object]).targets.size,0);mesh.geometry.dispose();mesh.material.dispose();f.dispose();});
test('collision tint restores all original colors and room cutaway shows colliding wall',()=>{const f=fixture(),head=f.listener.group.getObjectByName('head'),original=head.material.color.getHex();tintCollision(f.listener.group,true);assert.equal(head.material.color.getHex(),0xff303d);tintCollision(f.listener.group,false);assert.equal(head.material.color.getHex(),original);const room=createRoom(f.doc.room),right=room.surfaces.find(s=>s.name==='wall-right'),color=right.material.color.getHex(),camera=new THREE.PerspectiveCamera();camera.position.set(8,8,8);room.updateVisibility(camera,true);assert.equal(right.visible,false);tintCollision(right,true);room.updateVisibility(camera,true);assert.ok(right.visible);assert.ok(right.material.transparent);tintCollision(right,false);room.updateVisibility(camera,true);assert.equal(right.visible,false);assert.equal(right.material.color.getHex(),color);assert.equal(right.material.transparent,false);room.dispose();f.dispose();});
test('monitor entering the radiator colors the complete radiator red and restores it after separation',()=>{const f=fixture(),features=createRoomFeatureViews(f.doc.room,f.doc.roomFeatures),radiator=features.find(v=>v.group.name==='radiator'),body=radiator.group.getObjectByName('radiator-body'),original=body.material.color.getHex(),monitor=f.monitors[0].group,r=f.doc.roomFeatures.radiator;monitor.position.set(r.center,r.bottom,r.standoff+r.depth+.08);monitor.rotation.y=0;const hits=findMonitorCollisions([f.monitors[0]],[radiator.group],f.doc.room);assert.ok(hits.targets.has(radiator.group));tintCollision(radiator.group,hits.targets.has(radiator.group));assert.equal(body.material.color.getHex(),0xff303d);monitor.position.z=1;const clear=findMonitorCollisions([f.monitors[0]],[radiator.group],f.doc.room);tintCollision(radiator.group,clear.targets.has(radiator.group));assert.equal(body.material.color.getHex(),original);features.forEach(v=>v.dispose());f.dispose();});
