import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createDocument} from './src/model.js';
import {createRoom} from './src/room-view.js';
import {createSeatedListener} from './src/listener-view.js';
import {createStudioMonitor} from './src/monitor-view.js';
import {createTweeterRays} from './src/tweeter-rays.js';
import {MIN_LISTENING_DISTANCE,MIN_WALL_CLEARANCE,measureMonitorWallClearance,createMonitorWallWarnings} from './src/monitor-clearance.js';

function fixture(){const doc=createDocument(),room=createRoom(doc.room,doc.roomFeatures),listener=createSeatedListener(doc.objects[0]),monitors=doc.objects.filter(o=>o.type==='studio-monitor').map(createStudioMonitor);return {doc,room,listener,monitors,dispose(){room.dispose();listener.dispose();monitors.forEach(m=>m.dispose());}};}

test('Barefoot listening limit uses nearest real ear and colors each tweeter ray',()=>{const f=fixture(),near=createTweeterRays(f.monitors,f.listener,f.doc.room);assert.equal(MIN_LISTENING_DISTANCE,1);assert.equal(near.rayCount,2);for(const monitor of f.monitors){const ray=near.group.getObjectByName('ray-'+monitor.group.name),tweeter=monitor.getDriverCenters().find(d=>d.id==='tweeter').position,ears=['left','right'].map(side=>f.listener.group.getObjectByName('ear-'+side).getWorldPosition(new THREE.Vector3()));assert.ok(Math.abs(ray.userData.listeningDistance-Math.min(...ears.map(ear=>ear.distanceTo(tweeter))))<1e-9);assert.equal(ray.material.color.getHex(),ray.userData.tooClose?0xff303d:0x55e69a);}near.dispose();for(const monitor of f.monitors){monitor.group.position.z-=0.5;monitor.group.updateMatrixWorld(true);}const far=createTweeterRays(f.monitors,f.listener,f.doc.room);assert.equal(far.tooCloseCount,0);for(const monitor of f.monitors){const ray=far.group.getObjectByName('ray-'+monitor.group.name);assert.ok(ray.userData.listeningDistance>=1);assert.equal(ray.material.color.getHex(),0x55e69a);}far.dispose();f.dispose();});

test('wall warning measures full rotated envelope against bounded, even hidden walls',()=>{const f=fixture(),monitor=f.monitors[0];assert.equal(MIN_WALL_CLEARANCE,0.127);monitor.group.position.set(0.2,0.9245,0.3);monitor.group.rotation.y=0;monitor.group.updateMatrixWorld(true);const left=f.room.surfaces.find(s=>s.name==='wall-left');left.visible=false;const warnings=measureMonitorWallClearance([monitor],f.room.surfaces);const byWall=new Map(warnings.map(w=>[w.wall,w]));assert.ok(byWall.has('wall-left'));assert.ok(byWall.has('wall-front'));assert.ok(Math.abs(byWall.get('wall-left').distance-(0.2-0.267/2))<1e-5);assert.ok(Math.abs(byWall.get('wall-front').distance-(0.3-0.245))<1e-5);monitor.group.rotation.y=Math.PI/6;monitor.group.updateMatrixWorld(true);const view=createMonitorWallWarnings([monitor],f.room.surfaces);assert.ok(view.group.getObjectByName('wall-clearance-monitor-L-wall-left'));assert.ok(view.group.getObjectByName('wall-clearance-monitor-L-wall-front'));view.dispose();f.dispose();});

test('window opening does not create a false front-wall warning',()=>{const f=fixture(),monitor=f.monitors[0],niche=f.doc.roomFeatures.window;monitor.group.position.set(niche.center,0.9245,0.32);monitor.group.rotation.y=0;monitor.group.updateMatrixWorld(true);const warnings=measureMonitorWallClearance([monitor],f.room.surfaces);assert.ok(!warnings.some(w=>w.wall==='wall-front'));f.dispose();});
