import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {DEFAULT_ROOM,roomFromCentimeters,roomMetrics} from './src/model.js';
import {createRoom} from './src/room-view.js';
test('exact internal dimensions in meters and surface bounds',()=>{assert.deepEqual(roomFromCentimeters(247.7,371.5,260.5),DEFAULT_ROOM);const view=createRoom(DEFAULT_ROOM);view.group.updateMatrixWorld(true);assert.equal(view.surfaces.length,6);const bounds=new THREE.Box3();for(const s of view.surfaces)bounds.union(new THREE.Box3().setFromObject(s));const size=bounds.getSize(new THREE.Vector3());for(const [actual,expected] of [[size.x,2.477],[size.y,2.605],[size.z,3.715]])assert.ok(Math.abs(actual-expected)<1e-6);view.dispose();});
test('validation, metrics, cutaway and closed room',()=>{assert.throws(()=>roomFromCentimeters('',371.5,260.5));assert.throws(()=>roomFromCentimeters(Infinity,371.5,260.5));assert.equal(roomMetrics(DEFAULT_ROOM).area,2.477*3.715);const view=createRoom(DEFAULT_ROOM),camera=new THREE.PerspectiveCamera();camera.position.set(8,8,8);view.updateVisibility(camera,true);assert.equal(view.surfaces.find(s=>s.name==='ceiling').visible,false);assert.equal(view.surfaces.find(s=>s.name==='floor').visible,true);assert.equal(view.surfaces.find(s=>s.name==='wall-right').visible,false);view.updateVisibility(camera,false);assert.ok(view.surfaces.every(s=>s.visible));view.dispose();});

import {surfaceProjection} from './src/projection.js';
test('perpendicular orthographic projection of all six surfaces, both sides',()=>{const view=createRoom(DEFAULT_ROOM);for(const surface of view.surfaces){for(const side of ['inside','outside']){const {camera,target}=surfaceProjection(surface,1.6,side);assert.ok(camera.isOrthographicCamera);const direction=camera.getWorldDirection(new THREE.Vector3());assert.ok(Math.abs(direction.dot(surface.userData.outward)-(side==='inside'?1:-1))<1e-9);assert.ok(target.distanceTo(surface.position)<1e-9);const {width,height}=surface.geometry.parameters;assert.ok(camera.top*2>=height);assert.ok((camera.right-camera.left)>=width);}}view.dispose();});

import {createRoomHistory,parseRoomDocument} from './src/bench.js';
import {DIRECTIONS} from './src/orientation.js';
test('dimension history branches after undo, and imported files validate',()=>{const history=createRoomHistory();history.push({...DEFAULT_ROOM,width:3});assert.equal(history.undo().width,2.477);assert.ok(history.canRedo);history.push({...DEFAULT_ROOM,width:4});assert.equal(history.canRedo,false);assert.equal(history.undo().width,2.477);assert.equal(history.redo().width,4);const source={schemaVersion:1,units:'m',room:DEFAULT_ROOM,objects:[]};assert.deepEqual(parseRoomDocument(JSON.stringify(source)).room,DEFAULT_ROOM);assert.throws(()=>parseRoomDocument(JSON.stringify({...source,units:'cm'})));assert.throws(()=>parseRoomDocument(JSON.stringify({...source,room:{...DEFAULT_ROOM,width:-1}})));assert.deepEqual(DIRECTIONS,{north:[0,0,-1],east:[1,0,0],down:[0,-1,0]});});

import {createListenerRecord,createSeatedListener,SEATED_POSE} from './src/listener-view.js';
test('seated listener feet and casters touch the floor, ears at intended height',()=>{const record=createListenerRecord(DEFAULT_ROOM),view=createSeatedListener(record);view.group.updateMatrixWorld(true);for(const name of ['foot-left','foot-right','caster-0','caster-1','caster-2','caster-3','caster-4']){const box=new THREE.Box3().setFromObject(view.group.getObjectByName(name));assert.ok(Math.abs(box.min.y)<1e-6,name+' must touch floor');}const ear=view.group.getObjectByName('ear-left').getWorldPosition(new THREE.Vector3());assert.ok(Math.abs(ear.y-SEATED_POSE.earHeight)<1e-9);assert.equal(SEATED_POSE.stature,1.68);const bounds=new THREE.Box3().setFromObject(view.group);assert.ok(bounds.min.x>0&&bounds.max.x<DEFAULT_ROOM.width);assert.ok(bounds.min.z>0&&bounds.max.z<DEFAULT_ROOM.length);assert.ok(bounds.max.y<DEFAULT_ROOM.height);let triangles=0;view.group.traverse(m=>{if(m.isMesh)triangles+=m.geometry.index.count/3;});assert.ok(triangles<15000);view.dispose();});

test('listener placement survives JSON round trip and invalid placement is rejected',()=>{const object=createListenerRecord(DEFAULT_ROOM),document={schemaVersion:1,units:'m',room:DEFAULT_ROOM,objects:[object]};assert.deepEqual(parseRoomDocument(JSON.stringify(document)).objects,[object]);assert.throws(()=>parseRoomDocument(JSON.stringify({...document,objects:[null]})));assert.throws(()=>parseRoomDocument(JSON.stringify({...document,objects:[{...object,position:{...object.position,y:1}}]})));});

import {patchListener,maxSeatHeight,solveKnee} from './src/listener-model.js';
import {createDocumentHistory} from './src/history.js';
import {createDocument} from './src/model.js';
const lowerNames=['pelvis','thigh-left','thigh-right','knee-left','knee-right','shin-left','shin-right','ankle-left','ankle-right','foot-left','foot-right','chair-seat','chair-back','chair-column'];
function matrices(view,names){view.group.updateMatrixWorld(true);return names.map(name=>view.group.getObjectByName(name).matrixWorld.toArray());}
test('lean and head rotation leave every lower-body and chair transform unchanged',()=>{const record=createListenerRecord(DEFAULT_ROOM),base=createSeatedListener(record),lean=createSeatedListener(patchListener(record,{leanForward:30,leanSide:8})),head=createSeatedListener(patchListener(record,{headYaw:75,headPitch:35,headRoll:20}));assert.deepEqual(matrices(base,lowerNames),matrices(lean,lowerNames));assert.deepEqual(matrices(base,lowerNames),matrices(head,lowerNames));assert.deepEqual(matrices(base,['torso','shoulder-left','hand-right']),matrices(head,['torso','shoulder-left','hand-right']));assert.notDeepEqual(matrices(base,['head']),matrices(lean,['head']));assert.notDeepEqual(matrices(base,['head']),matrices(head,['head']));for(const view of [base,lean,head])view.dispose();});
test('feet stay on floor and segment lengths stay constant across supported body/chair ranges',()=>{for(const stature of [1.4,1.68,2])for(const seatHeight of [0.32,0.435,maxSeatHeight(stature)]){const record=patchListener(createListenerRecord(DEFAULT_ROOM),{stature,seatHeight}),view=createSeatedListener(record),s=stature/1.68;view.group.updateMatrixWorld(true);for(const name of ['foot-left','foot-right'])assert.ok(Math.abs(new THREE.Box3().setFromObject(view.group.getObjectByName(name)).min.y)<1e-6);assert.ok(Math.abs(view.group.getObjectByName('thigh-left').geometry.parameters.height-0.393*s)<1e-9);assert.ok(Math.abs(view.group.getObjectByName('shin-right').geometry.parameters.height-0.38*s)<1e-9);const seat=new THREE.Box3().setFromObject(view.group.getObjectByName('chair-seat'));assert.ok(Math.abs(seat.max.y-record.seatHeight)<1e-6);view.dispose();}assert.throws(()=>solveKnee([0,2,0],[0,0,0],0.4,0.4));});
test('pose migration, combined lean constraint and history retain full scene',()=>{const legacy={id:'listener-1',type:'seated-listener',stature:1.68,position:{x:1,y:0,z:1},yaw:0};const imported=parseRoomDocument(JSON.stringify({schemaVersion:1,units:'m',room:DEFAULT_ROOM,objects:[legacy]}));assert.equal(imported.objects[0].seatHeight,0.435);assert.equal(imported.objects[0].leanForward,10);const limited=patchListener(imported.objects[0],{leanForward:35,leanSide:20});assert.ok(Math.hypot(limited.leanForward/35,limited.leanSide/20)<=1+1e-9);const document=createDocument(),history=createDocumentHistory(document);document.objects[0].headYaw=30;history.push(document);assert.equal(history.undo().objects[0].headYaw,0);assert.equal(history.redo().objects[0].headYaw,30);assert.throws(()=>parseRoomDocument(JSON.stringify({...document,objects:[{...document.objects[0],headYaw:90}]})));});


test('head orientation and complete hand transforms remain fixed for all lean directions',()=>{for(const yaw of [0,0.7])for(const headSettings of [{headYaw:0,headPitch:0,headRoll:0},{headYaw:60,headPitch:30,headRoll:-20}]){const record={...createListenerRecord(DEFAULT_ROOM),yaw,...headSettings},base=createSeatedListener(record),baseRotation=base.group.getObjectByName('head').getWorldQuaternion(new THREE.Quaternion());for(const pose of [{leanForward:0,leanSide:0},{leanForward:35,leanSide:0},{leanForward:-10,leanSide:0},{leanForward:0,leanSide:20},{leanForward:0,leanSide:-20},{leanForward:11.7,leanSide:18.8}]){const view=createSeatedListener(patchListener(record,pose));assert.ok(baseRotation.angleTo(view.group.getObjectByName('head').getWorldQuaternion(new THREE.Quaternion()))<1e-7);assert.deepEqual(matrices(base,['hand-left','hand-right','wrist-left','wrist-right']),matrices(view,['hand-left','hand-right','wrist-left','wrist-right']));assert.deepEqual(matrices(base,lowerNames),matrices(view,lowerNames));view.dispose();}base.dispose();}});
test('arms keep rigid segment lengths and connect shoulders to fixed wrists across full lean envelope',()=>{for(const stature of [1.4,1.68,2])for(const seatHeight of [0.32,maxSeatHeight(stature)])for(let direction=0;direction<360;direction+=15){const angle=direction*Math.PI/180,record=patchListener(createListenerRecord(DEFAULT_ROOM),{stature,seatHeight,leanForward:Math.sin(angle)*(Math.sin(angle)>=0?35:10),leanSide:Math.cos(angle)*20}),view=createSeatedListener(record),s=stature/1.68;for(const tag of ['left','right']){const shoulder=view.group.getObjectByName('shoulder-'+tag).getWorldPosition(new THREE.Vector3()),elbow=view.group.getObjectByName('elbow-'+tag).getWorldPosition(new THREE.Vector3()),wrist=view.group.getObjectByName('wrist-'+tag).getWorldPosition(new THREE.Vector3());assert.ok(Math.abs(shoulder.distanceTo(elbow)-0.285*s)<1e-8);assert.ok(Math.abs(elbow.distanceTo(wrist)-0.27*s)<1e-8);}view.dispose();}});

test('elbows stay outside torso at strong lean in both lateral directions',()=>{for(const stature of [1.4,1.68,2])for(let direction=0;direction<360;direction+=10){const angle=direction*Math.PI/180,record=patchListener(createListenerRecord(DEFAULT_ROOM),{stature,leanForward:Math.sin(angle)*(Math.sin(angle)>=0?35:10),leanSide:Math.cos(angle)*20}),view=createSeatedListener(record),torso=view.group.getObjectByName('torso'),inverse=torso.matrixWorld.clone().invert(),radius=0.037*stature/1.68;for(const tag of ['left','right']){const p=view.group.getObjectByName('elbow-'+tag).getWorldPosition(new THREE.Vector3()).applyMatrix4(inverse);const clearance=(p.x/(1+radius/torso.scale.x))**2+(p.y/(1+radius/torso.scale.y))**2+(p.z/(1+radius/torso.scale.z))**2;assert.ok(clearance>=1,`${tag} elbow intersects torso at ${direction}°, clearance ${clearance}`);}view.dispose();}});
